### ISSUE TITLE
Moving tasks into subtasks is a bit clunky when there are many tasks

### ISSUE THREAD

**Issue by CodeNomadHQ** [PhilKes/Notally#21]
It's a bit hard to show in the video, but moving tasks up or down doesn’t work, and making a task a subtask fails half the time.

https://github.com/user-attachments/assets/112734e8-9f81-4bc4-ae3d-37bd2d46e1bb

**Comment by PhilKes** [comment]
It looks like you are trying to drag an item by clicking an holding onto the `TextView`, but you can only drag items up/down by pressing down on the drag-icon on the left (2 vertical bars). It would be too confusing if you can drag items by clicking on the TextView, because you still want to be able to select the text.

About the making tasks to subtasks not working, I am not sure why the `SwipeLayout` sometimes behaves odd, I will look into it if I can tweak it a bit. I definetely noticed that there is an unnecessary `adapter` notification when you change a task to a subtask/vice-versa (you can see these notifications if you switched task to subtask then the task quickly blinks once), perhaps I can remove that

**Comment by CodeNomadHQ** [comment]
I think I found the issue with moving subtasks; it seems to be related to my backup, which broke subtasks for some reason. However, testing a new note with a subtask works fine, and creating a new note also works well. I believe we can close this issue.
