### ISSUE TITLE
improving subtasks

### ISSUE THREAD

**Issue by CodeNomadHQ** [PhilKes/Notally#9]
Subtasks not working in widgets, not backed up when importing notes, and swiping back after pasting text in a task doesn't work.

**Comment by PhilKes** [comment]
Since I'm still working/refactoring the Sorting/ChangeHistory/ListItem model I will take a look at importing notes from older versions afterwards

**Comment by PhilKes** [comment]
I opened a separate issues for the support in widgets: https://github.com/PhilKes/Notally/issues/18
Importing notes with subtasks should also be fixed by https://github.com/PhilKes/Notally/pull/16

Can you elaborate on the swiping back after pasting text doesnt work? Perhaps you could open another issue for that

**Comment by CodeNomadHQ** [comment]
I’m going to close this issue and create a new one for the wiping back issue to keep things organized.
